# Basic Information 
title: Shuaifan (Collin) Xia
position: M.Eng. from Tongji University
affiliation: Étudiant d'Ingénieur à Télécom Paris
email: shuaifan.xia (at) telecom-paris.fr

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Collin, Shuaifan, 夏帅凡, Shuaifan Xia
description: Shuaifan Collin Xia's personal homdpage using The Minimal Light jekyll theme.
canonical: https://collin911.github.io/homepage/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=x4Y8uCAAAAAJ&hl=en/
cv_link: https://github.com/Collin911/myCV/blob/main/resume.pdf?raw=true
github_link: https://github.com/Collin911/
ORCID: https://orcid.org/0000-0002-9769-4373/
ieee_link: https://ieeexplore.ieee.org/author/37089595748/
linkedin: https://www.linkedin.com/in/ShuaifanX
#twitter: https://twitter.com/Azure_cx

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
